#!/usr/bin/env python3
#
# Copyright 2013 Simone Campagna
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

__author__ = "Simone Campagna"

import os
import re
import sys
import glob
import time
import shutil
import logging
import argparse
import calendar
import datetime
import collections
import configparser

class Ask(object):
    def __init__(self, answer='x'):
        self._answer = answer

    def ask(self, question):
        answer = self._answer
        while not answer in 'ANyn':
            answer = input(question + "? ([y]es/[n]o/[A]ll/[N]one) ")

        if answer in 'AN':
            self._answer = answer

        if answer in 'Ay':
            return True
        else:
            return False



class TDelta(object):
    def __init__(self, year=0, month=0, day=0, hour=0, minute=0, second=0):
        self.year = year
        self.month = month
        self.day = day
        self.hour = hour
        self.minute = minute
        self.second = second

    def __add__(self, dt):
        assert isinstance(dt, datetime.datetime)
        return self._make_datetime(
            year=self.year + dt.year, 
            month=self.month + dt.month, 
            day=self.day + dt.day, 
            hour=self.hour + dt.hour, 
            minute=self.minute + dt.minute, 
            second=self.second + dt.second, 
        )

    def __radd__(self, dt):
        assert isinstance(dt, datetime.datetime)
        return self.__add__(dt)

    def __sub__(self, dt):
        assert isinstance(dt, datetime.datetime)
        return self._make_datetime(
            year=self.year - dt.year, 
            month=self.month - dt.month, 
            day=self.day - dt.day, 
            hour=self.hour - dt.hour, 
            minute=self.minute - dt.minute, 
            second=self.second - dt.second, 
        )

    def __rsub__(self, dt):
        assert isinstance(dt, datetime.datetime)
        return self._make_datetime(
            year=dt.year - self.year,
            month=dt.month - self.month,
            day=dt.day - self.day,
            hour=dt.hour - self.hour,
            minute=dt.minute - self.minute,
            second=dt.second - self.second,
        )

    def _norm_month(self, year, month):
        while month < 1:
            month += 12
            year -= 1
        while month > 12:
            month -= 12
            year += 1
        return year, month

    def _make_datetime(self, year, month, day, hour, minute, second):
        while second < 0:
            minute -= 1
            second += 60
        while second >= 60:
            minute += 1
            second -= 60
        while minute < 0:
            hour -= 1
            minute += 60
        while minute >= 60:
            hour += 1
            minute -= 60
        while hour < 0:
            day -= 1
            hour += 24
        while hour >= 24:
            day += 1
            hour -= 24
        year, month = self._norm_month(year, month)
        while day < 1:
            month -= 1
            year, month = self._norm_month(year, month - 1)
            month_days = calendar.monthrange(year, month)[1]
            day += month_days
        year, month = self._norm_month(year, month)
        while True:
            month_days = calendar.monthrange(year, month)[1]
            if day <= month_days:
                break
            year, month = self._norm_month(year, month + 1)
            day -= month_days
        #print(year, month, day, hour, minute, second)
        return datetime.datetime(year, month, day, hour, minute, second)
      
class EntryList(set):
    def __init__(self, list_file, list_dir=None):
        self.list_file = os.path.abspath(list_file)
        if list_dir is None:
            list_dir = os.path.dirname(self.list_file)
        super().__init__()
        with open(self.list_file, "r") as f_in:
            for line in f_in:
                entry = line.strip()
                if not os.path.isabs(entry):
                      entry = os.path.join(list_dir, entry)
                for p_entry in glob.glob(entry):
                    p_entry = os.path.normpath(p_entry)
                    #print("*** {!r} -> {!r}".format(entry, p_entry))
                    self.add(p_entry)

    def __str__(self):
        return repr(self)

    def __repr__(self):
        return "{}(list_file={!r}, {})".format(self.__class__.__name__, self.list_file, super().__repr__())

class MetaHouseKeeper(type):
    def __new__(mcls, class_name, class_bases, class_dict):
        cls = super().__new__(mcls, class_name, class_bases, class_dict)
        unit_aliases = []
        cls.UNIT_DICT = {}
        for unit, aliases in cls.UNIT_ALIASES.items():
            unit_aliases.append(unit)
            unit_aliases.extend(aliases)
            cls.UNIT_DICT[unit] = unit
            for alias in aliases:
                cls.UNIT_DICT[alias] = unit
        unit_aliases.sort(key=lambda x: len(x), reverse=True)
        #print('([+-]?[1-9]\d+|[+-]?0)\s*({})'.format('|'.join(unit_aliases)))
        cls.RE_TOKEN = re.compile('([+-]?[1-9]\d*|[+-]?0)\s*({})'.format('|'.join(unit_aliases)))
        cls.RE_SEP = re.compile('[,\s]*')
        return cls

class HouseKeeper(metaclass=MetaHouseKeeper):
    MODE_INTERACTIVE = 'interactive'
    MODE_FORCE = 'force'
    MODES = (MODE_FORCE, MODE_INTERACTIVE)
    DEFAULT_MODE = MODE_INTERACTIVE
    DEFAULT_TIME_ATTRIBUTE = "st_mtime"

    TIME_FORMAT = "%Y%m%d %H:%M:%S"
    TIME_FORMATS = (TIME_FORMAT, "%Y%m%d")
    UNIT_ALIASES = {
        'year': ('years', ),
        'month': ('months', ),
        'week': ('weeks', ),
        'day': ('days', ),
        'hour': ('hours', ),
        'minute': ('minutes', ),
        'second': ('seconds', ),
    }
    NOW = datetime.datetime.now()
    HOUSEKEEPER_LIST = ".housekeeper"
    class Selection(collections.namedtuple('Selection', ('pattern', 'ref_time', 'remove_dirs', 'remove_files', 'remove_links', 'follow_symlinks', 'revert'))):
        def __new__(cls, pattern, ref_time, *, remove_dirs=True, remove_files=True, remove_links=True, follow_symlinks=False, revert=False):
            return super().__new__(
                cls,
                pattern=pattern,
                ref_time=ref_time,
                remove_dirs=remove_dirs,
                remove_links=remove_links,
                remove_files=remove_files,
                follow_symlinks=follow_symlinks,
                revert=revert,
            )


    def __init__(self, logger, *, mode=DEFAULT_MODE, dry_run=False, time_attribute):
        self.logger = logger
        self.mode = mode
        self.dry_run = dry_run
        self.time_attribute = time_attribute
        self.ask_clean = Ask()
        self._visited = set()
        self._list_dirs = {}

    @classmethod
    def make_ref_time(cls, ref_time_s):
        # zero
        if ref_time_s.strip() == "0":
            return cls.NOW
        # absolute datetime
        for fmt in cls.TIME_FORMATS:
            try:
                return datetime.datetime.strptime(ref_time_s, fmt)
            except ValueError:
                pass
        # relative datetime
        s = ref_time_s
        tokens = []
        offset = 0
        while s:
            m_sep = cls.RE_SEP.match(s)
            #print("sep: <{}> -> {}".format(s, m_sep))
            if m_sep:
                b, e = m_sep.span()
                s = s[e:]
                offset += e
            m_token = cls.RE_TOKEN.match(s)
            #print("token: <{}> -> {}".format(s, m_token))
            if m_token:
                b, e = m_token.span()
                s = s[e:]
                offset += e
                tokens.append(m_token.groups())
            else:
                raise ValueError("invalid ref_time {!r}: unparsed token {!r}".format(ref_time_s, ref_time_s[offset:]))
        tdelta = TDelta()
        for num, unit in tokens:
            num = int(num)
            unit = cls.UNIT_DICT[unit]
            if unit == 'year':
                tdelta.year += num
            elif unit == 'month':
                tdelta.month += num
            elif unit == 'week':
                tdelta.day += 7 * num
            elif unit == 'day':
                tdelta.day += num
            elif unit == 'hour':
                tdelta.hour += num
            elif unit == 'minute':
                tdelta.minute += num
            elif unit == 'second':
                tdelta.second += num
            else:
                raise ValueError("invalid unit {}".format(unit))
        return cls.NOW - tdelta

    def clean(self, *selections):
        for selection in selections:
            self.logger.info("pattern={pattern!r}, ref_time={ref_time!r}, remove_dirs={s.remove_dirs!r}, remove_links={s.remove_links!r}, remove_files={s.remove_files!r}, follow_symlinks={s.follow_symlinks!r}, revert={s.revert!r}".format(
                pattern=selection.pattern,
                ref_time=selection.ref_time.strftime(self.TIME_FORMAT),
                s=selection))
            self.clean_selection(selection)
       
    @classmethod
    def younger_than(cls, entry_time, ref_time):
        return entry_time >= ref_time

    @classmethod
    def older_than(cls, entry_time, ref_time):
        return entry_time < ref_time

    def clean_selection(self, selection):
        pattern = selection.pattern
        ref_time = selection.ref_time
        remove_dirs = selection.remove_dirs
        remove_links = selection.remove_links
        remove_files = selection.remove_files
        follow_symlinks = selection.follow_symlinks
        revert = selection.revert
   
        if revert:
            mismatch_message = 'old'
            match_function = self.younger_than
        else:
            mismatch_message = 'recent'
            match_function = self.older_than

        if not isinstance(ref_time, datetime.datetime):
            ref_time = self.make_ref_time(ref_time)
        for entry in glob.glob(pattern):
            if not os.path.lexists(entry):
                continue
            entry = os.path.normpath(os.path.abspath(entry))
            if not os.path.lexists(entry):
                continue
            if entry in self._visited:
                self.logger.debug("skipping aleady visited entry {}".format(entry))
                continue
            entry_stat = os.stat(entry, follow_symlinks=False) # get stats of the link
            entry_seconds = getattr(entry_stat, self.time_attribute)
            entry_time = datetime.datetime(*time.localtime(entry_seconds)[:6])
            entry_type = None
            entry_remover = None
            must_remove = True
            list_dirs = []
            entry_is_link = False
            if os.path.islink(entry):
                # link
                entry_type = 'symbolic link'
                entry_remover = self.remove_link
                if not remove_links:
                    must_remove = False
                entry_is_link = True
            elif os.path.isdir(entry):
                # dir
                entry_type = 'directory'
                entry_remover = self.remove_dir
                if not remove_dirs:
                    must_remove = False
                list_dirs.append(entry)
            elif os.path.isfile(entry):
                # file
                entry_type = 'file'
                entry_remover = self.remove_file
                if not remove_files:
                    must_remove = False
            else:
                self.logger.warning("skipping unmanaged entry {}".format(entry))
                continue
            self._visited.add(entry)
            list_dirs.append(os.path.dirname(entry))
            if not must_remove:
                self.logger.debug("skipping {} {}".format(entry_type, entry))
                continue
            entry_list = None
            for list_dir in list_dirs:
                if list_dir in self._list_dirs:
                    entry_list = self._list_dirs[list_dir]
                else:
                    list_file = os.path.join(list_dir, self.HOUSEKEEPER_LIST)
                    if os.path.exists(list_file):
                        self.logger.debug("reading config file {}".format(list_file))
                        entry_list = EntryList(list_dir=list_dir, list_file=list_file)
                        self._list_dirs[list_dir] = entry_list
                    else:
                        self._list_dirs[list_dir] = None
                if entry_list is not None:
                    break
            if entry_list is not None:
                #print(entry_list)
                if entry in entry_list:
                    must_remove = False    
                    self.logger.debug("skipping {} {} (see {})".format(entry_type, entry, entry_list.list_file))
                    continue
            if match_function(entry_time, ref_time):
                self.logger.info("{time_attribute}={entry_time!r} ref_time={ref_time!r}: removing {entry_type:13} {entry!r}".format(
                    pattern=pattern,
                    entry_type=entry_type,
                    entry=entry,
                    time_attribute=self.time_attribute,
                    entry_time=entry_time.strftime(self.TIME_FORMAT),
                    ref_time=ref_time.strftime(self.TIME_FORMAT)))
                if self.must_remove("{} {}".format(entry_type, entry), self.mode):
                    entry_remover(entry)
            else:
                self.logger.debug("skipping {} {} {}".format(mismatch_message, entry_type, entry))
            if entry_is_link:
                sub_entry = os.path.realpath(entry)
                if sub_entry != entry:
                    self.logger.debug("following symbolic link {} -> {}".format(entry, sub_entry))
                    sub_selection = selection._replace(pattern=sub_entry)
                    self.clean_selection(sub_selection)
        
    def must_remove(self, message, mode):
        if mode == self.MODE_INTERACTIVE:
            return self.ask_clean.ask("remove {}".format(message))
        elif mode == self.MODE_FORCE:
            return True
        else:
            assert False

    def remove_dir(self, entry):
        if self.dry_run:
            self.logger.warning("DRY-RUN> removing directory {}".format(entry))
        else:
            self.logger.info("removing directory {}".format(entry))
            shutil.rmtree(entry, ignore_errors=True)

    def remove_link(self, entry):
        if self.dry_run:
            self.logger.warning("DRY-RUN> removing symbolic link {}".format(entry))
        else:
            self.logger.info("removing symbolic link {}".format(entry))
            os.remove(entry)

    def remove_file(self, entry):
        if self.dry_run:
            self.logger.warning("DRY-RUN> removing file {}".format(entry))
        else:
            self.logger.info("removing file {}".format(entry))
            os.remove(entry)
            
class HouseKeeperConfig(configparser.ConfigParser):
    def __init__(self):
        super().__init__()
        self['DEFAULT'] = {
            'ref_time': '',
            'remove_dirs': 'True',
            'remove_links': 'True',
            'remove_files': 'True',
            'follow_symlinks': 'False',
            'revert': 'False',
        }

def _bool(bool_string):
    if bool_string == "True":
        return True
    elif bool_string == "False":
        return False
    else:
        try:
            i = int(bool_string)
            return bool(i)
        except ValueError:
            raise ValueError("invalid boolean value {!r}".format(bool_string))
def main():
    def pattern_type(s):
        if not ':' in s:
            raise ValueError("invalid value {!r}: must be <pattern>:<reference time>")
        pattern, ref_time_s = s.rsplit(':', 1)
        try:
            ref_time = HouseKeeper.make_ref_time(ref_time_s)
        except Exception as e:
            sys.stderr.write("ERR: {}: {}\n".format(e.__class__.__name__, e))
            raise
        return pattern, ref_time

    common_parser = argparse.ArgumentParser(add_help=False)

    common_parser.add_argument("--verbose", "-v",
        action="store_true",
        default=False,
        help="verbose mode")

    common_parser.add_argument("--debug", "-d",
        action="store_true",
        default=False,
        help="debug mode")

    common_parser.add_argument("--dry-run", "-D",
        action="store_true",
        default=False,
        help="dry run (do not delete)")

    time_group = common_parser.add_mutually_exclusive_group(required=False)

    time_group.add_argument("--ctime",
        dest="st_time_attribute",
        action="store_const",
        const="st_ctime",
        default=HouseKeeper.DEFAULT_TIME_ATTRIBUTE,
        help="use inode change time")
   
    time_group.add_argument("--mtime",
        dest="st_time_attribute",
        action="store_const",
        const="st_mtime",
        default=HouseKeeper.DEFAULT_TIME_ATTRIBUTE,
        help="use file modification time")
   
    time_group.add_argument("--atime",
        dest="st_time_attribute",
        action="store_const",
        const="st_atime",
        default=HouseKeeper.DEFAULT_TIME_ATTRIBUTE,
        help="use file access time")
   
    mode_group = common_parser.add_mutually_exclusive_group(required=False)

    mode_group.add_argument("--interactive", "-i",
        dest="mode",
        action="store_const",
        const=HouseKeeper.MODE_INTERACTIVE,
        default=HouseKeeper.DEFAULT_MODE,
        help="interactive (ask before deleting)")

    mode_group.add_argument("--force", "-f",
        dest="mode",
        action="store_const",
        const=HouseKeeper.MODE_FORCE,
        default=HouseKeeper.DEFAULT_MODE,
        help="force (delete files without asking)")

    parser = argparse.ArgumentParser(parents=[common_parser])

    parser.add_argument("--config", "-c", 
        metavar="C",
        type=str,
        action="append",
        default=[],
        help="add config filename")

    parser.add_argument("--pattern", "-p",
        metavar="P:RT",
        dest="patterns",
        action="append",
        type=pattern_type,
        default=[],
        help="add pattern and reference time")

    parser.add_argument("--remove-dirs",
        dest="remove_dirs",
        action="store_true",
        default=True,
        help="remove directories")
    parser.add_argument("--ignore-dirs",
        dest="remove_dirs",
        action="store_false",
        default=True,
        help="do not remove directories")

    parser.add_argument("--remove-links",
        dest="remove_links",
        action="store_true",
        default=True,
        help="remove links")
    parser.add_argument("--ignore-links",
        dest="remove_links",
        action="store_false",
        default=True,
        help="do not remove links")

    parser.add_argument("--remove-files",
        dest="remove_files",
        action="store_true",
        default=True,
        help="remove files")
    parser.add_argument("--ignore-files",
        dest="remove_files",
        action="store_false",
        default=True,
        help="do not remove files")

    parser.add_argument("--revert", "-r",
        action="store_true",
        default=False,
        help="revert (delete files younger than ref_time)")

    parser.add_argument("--follow-symlinks", "-l",
        action="store_true",
        default=False,
        help="clean also files pointed to by symbolic links")

    args = parser.parse_args()

    logger = logging.getLogger("CLEAN_DIRS")
    handler = logging.StreamHandler()
    log_level = logging.WARNING
    if args.debug:
        log_level = logging.DEBUG
    elif args.verbose:
        log_level = logging.INFO
    else:
        log_level = logging.WARNING
    logger.addHandler(handler)
    logger.setLevel(log_level)
    handler.setLevel(log_level)

    g_options = {}
    for o in 'remove_dirs', 'remove_links', 'remove_files', 'follow_symlinks', 'revert':
        g_options[o] = getattr(args, o)

    try:
        selections = []
        if args.config:
            config = HouseKeeperConfig()
            config.read(args.config)
            for pattern, pattern_data in config.items():
                if not os.path.isabs(pattern):
                    pattern = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(args.config)), pattern))
                selection = HouseKeeper.Selection(pattern=pattern, ref_time=pattern_data['ref_time'])
                for field_name in 'remove_dirs', 'remove_links', 'remove_files', 'follow_symlinks', 'revert':
                    setattr(selection, field_name, _bool(pattern_data[field_name]))
                selections.append(selection)
        if args.patterns:
            for pattern, ref_time in args.patterns:
                selection = HouseKeeper.Selection(pattern=pattern, ref_time=ref_time, **g_options)
                selections.append(selection)
                #apply_patterns(logger, args.ref_time, *args.patterns)
    
        housekeeper = HouseKeeper(logger=logger, dry_run=args.dry_run, mode=args.mode, time_attribute=args.st_time_attribute)
        housekeeper.clean(*selections)
    except Exception as e:
        if args.debug:
            import traceback
            traceback.print_exc()
        logger.critical("ERR: {}: {}".format(e.__class__.__name__, e))
        sys.exit(1)

if __name__ == "__main__":
    main()
